name: ai
description: A AI terminal helper for developers.
version: 0.3.0

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  http: ^1.4.0
  path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
